### PR TITLE
Security dependencies

### PR DESCRIPTION
**Pull request by clarkio**
# !!Please review #26 first!!

## Purpose

* address dependencies with vulnerabilities

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## How to Test
*  Get the code

```
git clone git@github.com:Azure-Samples/angular-cosmosdb.git
cd angular-cosmosdb
git checkout security-dependencies
npm install
```

* Test the code

```
snyk test
npm audit
```

## What to Check
Verify that the following are valid
* snyk shows no vulnerabilities after `snyk test`
* npm audit only shows the following after running `npm audit`: `6 vulnerabilities found`

### CODE REVIEW

**Comment by clarkio** [comment]
Thanks @johnpapa. Will merge this after #26

**Comment by johnpapa** [comment]
please fix the merge conflicts, then we'll merge @clarkio

**Comment by clarkio** [comment]
@johnpapa conflicts resolved. Please double check the "verify" steps from the PR to confirm everything is still good to go.

**Comment by johnpapa** [comment]
@clarkio merged. please do one more pass thru. and make sure the docs are ready to roll

**Pull request merged**
