### PR TITLE
Fix mongoose

### PR DESCRIPTION
**Pull request by clarkio**
## Purpose

* Fix for [#8436](https://github.com/MicrosoftDocs/azure-docs/issues/8436)

## Does this introduce a breaking change?

```
[x] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone git@github.com:Azure-Samples/angular-cosmosdb.git
cd angular-cosmosdb
git checkout fix-mongoose
npm install
```

## What to Check
Verify that the following are valid
* You can add a hero
* You can add more heroes
* You can update a hero
* You can delete a hero

### CODE REVIEW

**Comment by clarkio** [comment]
@johnpapa sure

From [#8436](https://github.com/MicrosoftDocs/azure-docs/issues/8436):
mongoose reserves the key `id` and is trying to create values for it in new documents so changing the model to use the key as `uid` instead fixes the problem.

**Comment by rbmathis** [comment]
Hi all - Thanks for the help!  Unfortunately, still no joy.  The initial insert works fine, but any insert afterwards throws the duplicate key error.  I did confirm that all the files are now using "uid" instead of "id", but it doesn't seem to matter.  If there is *any* record in the mongo db, nothing else can be inserted.
errormessage
existinghero
newhero

**Comment by clarkio** [comment]
@rbmathis if you're using the same instance of the MongoDB from earlier (when you used `id`) it's still using the old schema. I'm not familiar with manually changing an existing schema for a collection in MongoDB but if you're just using a sample database you can delete the collection and let the app recreate it with the new schema.

**Comment by johnpapa** [comment]
Something must have changed, since this worked before. Can you verify what happened there?

Let's add a `CHANGELOG.md` and note this, @clarkio

**Comment by clarkio** [comment]
@johnpapa I've not found a root cause other than it has to do with a field being indexed that must be unique and somehow a field is potentially being populated with a `null` value. Changing the field to be `uid`  avoids the conflict with the mongodb built in field around `_id` and `id`

**Comment by johnpapa** [comment]
ok ... let's move forward once you enter the changelog. ok? @clarkio

**Comment by clarkio** [comment]
@johnpapa changelog has been updated and version bumped

**Comment by johnpapa** [comment]
merged! thanks everyone!

**Pull request merged**
